### ISSUE TITLE
Get devices primary IDs

### ISSUE THREAD

**Issue by robertsLando** [Apollon77/node-mbus#10]
Is there a way to know devices primary id? SlaveInformation just contains device secondary ID. I also think that the scan is made throught primary IDs because if 2 devices has the same primary id it doesn't find both but only one

**Comment by Apollon77** [comment]
To be honest: I have no idea, had the same question in my mind too and finally don't think  that this is available ... Else we need to check the protocol :-)

Also SlaveInformation is not containing the full "secondary ID"!! This is more the device ID, yes these ae the first positions of the secondary-ID but then more comes after a Letter

**Comment by robertsLando** [comment]
Yes it is the device Id that I usually use also as secondary ID with other softwares scan. In my code I use this function to get what you call deviceID: 

```javascript
  function parseSecondaryID(id){
      id = id.substr(0,8);
      id = parseInt(id); //remove leading 0
      return id.toString();
    }
```

Honestly: I don't know the mean of other chars in the secondary id provided from the scan but this is how I parse them and seems to work for now

**Comment by Apollon77** [comment]
Correct, But when using the Secondary-ID to query the device data then you ned to use the "full" secondary ID ... As I understood the second part is needed to mae the ID "worldwide unique"

**Comment by Apollon77** [comment]
Not possible
