### ISSUE TITLE
Cannot rebuild

### ISSUE THREAD

**Issue by DanMinaj** [Apollon77/node-mbus#18]
After downloading I run 'npm i' and i am getting this error preventing me:

Warning: Missing input files:
C:\Users\David\Desktop\node-mbus-master\build\..\libmbus\mbus\mbus-tcp.c
C:\Users\David\Desktop\node-mbus-master\build\..\libmbus\mbus\mbus-protocol-aux.c
C:\Users\David\Desktop\node-mbus-master\build\..\libmbus\mbus\mbus-serial.c
C:\Users\David\Desktop\node-mbus-master\build\..\libmbus\mbus\mbus-protocol.c
C:\Users\David\Desktop\node-mbus-master\build\..\libmbus\mbus\mbus.c
C:\Users\David\Desktop\node-mbus-master\build\..\libmbus\win\termiWin.c
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  mbus-protocol-aux.c
  mbus-protocol.c
  mbus-serial.c
  mbus-tcp.c
c1 : fatal error C1083: Cannot open source file: '..\libmbus\mbus\mbus-tcp.c':
No such file or directory [C:\Users\David\Desktop\node-mbus-master\build\libmbu
s.vcxproj]
c1 : fatal error C1083: Cannot open source file: '..\libmbus\mbus\mbus-protocol
.c': No such file or directory [C:\Users\David\Desktop\node-mbus-master\build\l
ibmbus.vcxproj]
c1 : fatal error C1083: Cannot open source file: '..\libmbus\mbus\mbus-serial.c
': No such file or directory [C:\Users\David\Desktop\node-mbus-master\build\lib
mbus.vcxproj]
c1 : fatal error C1083: Cannot open source file: '..\libmbus\mbus\mbus-protocol
-aux.c': No such file or directory [C:\Users\David\Desktop\node-mbus-master\bui
ld\libmbus.vcxproj]
  mbus.c
  termiWin.c
c1 : fatal error C1083: Cannot open source file: '..\libmbus\mbus\mbus.c': No s
uch file or directory [C:\Users\David\Desktop\node-mbus-master\build\libmbus.vc
xproj]
c1 : fatal error C1083: Cannot open source file: '..\libmbus\win\termiWin.c': N
o such file or directory [C:\Users\David\Desktop\node-mbus-master\build\libmbus
.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\David\Desktop\node-mbus-master
gyp ERR! node -v v10.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-mbus@0.5.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-mbus@0.5.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\David\AppData\Roaming\npm-cache\_logs\2018-07-11T12_11_12_073Z-debug.log

C:\Users\David\Desktop\node-mbus-master

**Comment by Apollon77** [comment]
It seems that the relevant files are missing for you ... they should be in the package. Only a "prepublish" rule exists what is in the package.json. I have no idea if this may be executed by a rebuild? But then you should have more messages because he would try to checkout them newly from the relevant git.

for now: reinstall package and try to reproduce please. never experienced that before
