### ISSUE TITLE
Cant seem to get the correct value Id info

### ISSUE THREAD

**Issue by dazzlersa** [Apollon77/node-mbus#26]
Hi

Hoping for some help.
I am using your library in a new driver of mine where the mbus device has a lot if value Id's.
But I cant seem to figure out what data it is outputting and how to get to the end of the results.

I am hoping these pictures can help me explain a bit better:
There are the current "clipped" results:
![image](https://user-images.githubusercontent.com/892876/52941103-b656b400-3370-11e9-9bba-0c8e8842d047.png)

But these are the values I was expecting to see:
![image](https://user-images.githubusercontent.com/892876/52941386-56acd880-3371-11e9-9ed2-f63b2861512d.png)

Any assistance would be greatly appreciated.

**Comment by Apollon77** [comment]
Please try node-mbus@experimental that is 0.6.1 ... that should return all data. But the order is unchangeable because comes directly from the device that way.

**Comment by dazzlersa** [comment]
Brilliant. Thank you, worked perfectly first time.
