### ISSUE TITLE
Asyncronous Reading of Secondar Addresses

### ISSUE THREAD

**Issue by dazzlersa** [Apollon77/node-mbus#59]
Firstly, thank you to everyone who has contributed to this library. It has honestly helped me a lot.
I was wondering is it is even a possibility to be able to read mbus devices (through the TCP/IP transparent gateway) in parallel (async) versus reading one after the other (synchronous).

I have multiple sites that have about 750 devices to read on each Gateway. It takes forever. Almost an hour sometimes.
And I read my devices every hour lol. But I want to be able to read in 15-minute intervals, but the driver is bottlenecking the ingestion.

Any ideas or suggestions (If this is even possible)?

TIA Darryl

**Comment by Apollon77** [comment]
Unthinkable this will not work from what I understood from the mbus protocol. You first select the device you want to talk to and then you send commands. Communication is done on two wires and do only one device can talk at one timepoint. 

With this in mind .... no, communicating in parallel with multiple devices on one master is not possible.

**Comment by Apollon77** [comment]
Ps: the library encapsulates this so in the library you can generate calls „in parallel“ and the library will process them sequentially.

**Comment by Apollon77** [comment]
Aahhhh you meaned tcp ... most gateways that I know just pass the binary data from
Tcp through to the mbus line ... and do they have the same Limitation.

**Comment by dazzlersa** [comment]
Thanks for the prompt response. I had a feeling, it was just a shot in the dark. 

So who is going to invent a more efficient way to communicate over 2 wires? lol

**Comment by Apollon77** [comment]
;-)
