### ISSUE TITLE
Where is the Unit value coming from?

### ISSUE THREAD

**Issue by wmmihaa** [Apollon77/node-mbus#64]
We're trying to make sense of the `Unit` field of the data record, which seem to lack consistency. Here are some examples:
* "Volume (m m^3)"
* "External temperature (1e-2  deg C)"
* "Energy (100 Wh)"

I understand that reverse-engineering the field might never get fully accurate, but if feels like it's just a free text field. Having a look at the [libmbus library](https://github.com/rscada/libmbus/blob/027f6fb6899b902bdd7d0b3230ecccc24f6bc6c3/mbus/mbus-protocol-aux.c), it looks like pretty structured, but perhaps the Unit value is derived from somewhere else?

Cheers

**Comment by Apollon77** [comment]
All data come directly unfiltered from libmbus and the scale factors out of the data.

**Comment by Apollon77** [comment]
The library internally uses the returned data objects from libmbus (you should get the same data with the xml/json output from libmbus cli tools

**Comment by wmmihaa** [comment]
Thank you...
so for "Volume (m m^3)" "**m**" derives from the data and "**m^3**" form libmbus?

**Comment by wmmihaa** [comment]
For instance... why do I get "Energy (10 kWh)" and not "Energy (1e1 kWh)"?

BTW...I understand this is issue has nothing to do with node-mbus!
